### ISSUE TITLE
resilient typedefs

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#2202] opened 2021-02-22 23:22 UTC
Currently, it is an error in the zson/zng spec and code to redefine a type name.   This should be relaxed though discouraged so that type conflicts can be accommodated and the ZSON stream remains valid.  A Z query will continue to operate just fine with a changed type stream... it just might not do what the user expects.  The enforcement of a type name scheme in which type name changes are rejected is left outside the scope of the Z data model, type system, and specifications.

**Comment by philrz** [comment] 2021-03-16 00:12
Closing as a duplicate of #1568.

**Closed by philrz** 2021-03-16 00:12 UTC
