### ISSUE TITLE
ast Op names

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#2134] opened 2021-02-15 00:54 UTC
We should unify the names of AST node and Ops.

The Op names in each of the AST nodes should have a string name that is the same as the ast type.

For example, ast.Foo should have an Op with value "Foo".

In terms of all the Expr nodes we should change Expression to Expr and be consistent throughout.

**Comment by philrz** [comment] 2021-03-16 00:07
We've recognized this one as a duplicate of #2222, so closing.

**Closed by philrz** 2021-03-16 00:07 UTC
Labels: duplicate
