### ISSUE TITLE
keys-only groupby

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1500] opened 2020-10-15 22:20 UTC
There is no way to do a group-by with just keys.  We should have a "groupby" keyword that lets you specify a groupby proc with no aggregations.  Hopefully, the groupby code will "just work" with no reducers, but if not, it should be easy to fix.

**Comment by henridf** [comment] 2020-10-15 22:26
The groupby by code should work with no reducers; at least it did handle reducer-less ASTs in some point in the recent past.

The ZQL syntax part of this issue is covered in #821. Back when we'd discussed that one at sync, we'd settled on `... | by keys | ` (https://github.com/brimsec/zq/issues/821#issuecomment-639031306).

**Comment by henridf** [comment] 2020-10-15 22:37
> at least it did handle reducer-less ASTs in some point in the recent past.

that's zar indexing in https://github.com/brimsec/zq/pull/816 ... it looks like we've since added reducers to those groupby's.

**Comment by mccanne** [comment] 2020-10-15 22:50
For syntax, what about just allowing the existing syntax with nothing, e.g.,
```
search | by foo,bar | ...
```

**Comment by mccanne** [comment] 2020-10-17 00:51
Yes, redundant with #821

**Comment by philrz** [comment] 2020-10-27 19:31
Per the prior comment, I'm closing this as a duplicate of #821.

**Closed** 2020-10-27 19:31 UTC
Labels: duplicate
